volumes:
  pg_data:
  static:
  media:
  frontend_build:

services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: nikitarachkov1/foodgram_backend:latest
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
    
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
      - media:/media
      - frontend_build:/usr/share/nginx/html
      - ./docs:/usr/share/nginx/html/docs
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - backend
  
  export-frontend:
    image: nikitarachkov1/foodgram_frontend:latest
    command: sh -lc 'cp -r /usr/share/nginx/html/* /export/  cp -r /app/build/* /export/  cp -r /build/* /export/'
    volumes:
      - frontend_build:/export
 